version: '3'

services:

  base_xenial:
    build:
        context: ./
        dockerfile: Dockerfile._base
        args:
                - base_image=ubuntu:16.04
                - base_dir=/docker
    image: base_xenial

  bitcoin.base_xenial:
    depends_on:
        - base_xenial
    build:
        context: ./
        dockerfile: bitcoin/Dockerfile._base
        args:
                - base_image=base_xenial
    image: bitcoin/base_xenial

  bitcoin.ubuntu:
    depends_on:
        - bitcoin.base_xenial
    build:
        context: ./
        dockerfile: bitcoin/Dockerfile.ubuntu
    image: bitcoin/ubuntu
    container_name: bitcoin.ubuntu
    volumes:
        - ${PROJECTS_DIR:-..}/bitcoin:/projects/bitcoin
    ports:
        - "8332-8333:8332-8333"
        - "18332-18333:18332-18333"